### ISSUE TITLE
Debugging help

### ISSUE THREAD

**Issue by JamesCordell** [SamuelBrucksch/wifibroadcast_osd#5]
Hi

First off, nice osd by the way, this project is amazing, good work.

How would I run this osd on a single pi, that has the telemetry feed from the flight controller, overlaid with the cameras image output to the hdmi or cvbs signal for simple debugging and testing. i.e no wifi stuff.

**Comment by SamuelBrucksch** [comment]
Hi this is part of the new easy wifibroadcast images of rodizio from fpv-community.de. it runs out ofthe box so maybe try that first.
